apiVersion: v2
name: et-cos
home: https://github.com/hmcts/et-ccd-callbacks
version: 0.0.6
description: HMCTS Employment Tribunals CCD Callbacks service
maintainers:
  - name: HMCTS Employment Tribunals Team
dependencies:
  - name: java
    version: 3.6.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
